language: objective-c
matrix:
  include:
    - osx_image: xcode8.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
script:
  - xctool -workspace travisPractice01.xcworkspace -scheme travisPractice01 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace travisPractice01.xcworkspace -scheme travisPractice01 -destination 'platform=iOS Simulator,name=iPhone 6' test
