language: objective-c
matrix:
  include:
    - osx_image: xcode8.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
script:
  - xcodebuild test -scheme travisPractice01 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
