language: objective-c
osx_image: xcode8.2
xcode_project: travisPractice01.xcodeproj # path to your xcodeproj folder
xcode_scheme: travisPractice01Tests

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
