language: objective-c
matrix:
  include:
    - osx_image: xcode8.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
script:
  - xctool -workspace YOURPROJECT.xcworkspace -scheme YOURSCHEME -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace YOURPROJECT.xcworkspace -scheme YOURSCHEME -destination 'platform=iOS Simulator,name=iPhone 6' test
